---
title: "Multiplying numbers from 1 to 10 by a multiplier"
author: "Hermina & Yvonne and here one more change" 
date: "Last compiled on `r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      smooth_scroll: false
---

Attribution: this code is modified from `reproducibility.Rmd`. Indicate here if you used ChatGPT or other AI tools to help you write the code.


# Introduction

The goal of this code is to teach students about reproducibility principles:

1. Annotate: explain what you're doing and _why_

    - using script headers and other Rmarkdown features (like this list!)
  
    - commenting your code
  
    - using meaningful & human-readable variable names

2. Automate: make your decisions explicit using code

    - use a scripting language to run your analyses
    
    - use find+replace to change variable names
    
    - automate the naming of your output files to include parameter values in the filename

3. Hoard: keep (almost) everything

    - store raw data *and* intermediate steps in data processing
  
    - store code *and* progress on code (i.e., use version control)
    
    - backup your work regularly (daily!)
    
    - note down the exact versions of software and packages

4. Share: provide access to your work

    - save versions using Git
  
    - use GitHub to upload the versions to their online server
  

# Run the code

This code multiplies the numbers from 1 to 10 by a constant then saves the output to a comma separated values (`.csv`) file.

```{r run&store_multiples}
# Function to multiply integers from 1 to 10 by a parameter value
get.multiples1to10 <- function(multiplier){
  numbers <- 1:10
  return(multiplier * numbers)
}

# Loop over parameter values 2, 3, and 4
for(current_value in 2:4){
  # Get the multiples
  results <- get.multiples1to10(multiplier = current_value)
  
  # Construct the filename
  the_filename <- paste("multiples1to10--multiplier", current_value, ".csv")
  
  # Write the vector directly to CSV
  write.csv(results, file = the_filename, row.names = FALSE)
}
```


